name: Demo Advanced GitHub Actions

on:
  push:
    branches: [ "main", "dev" ]     # запуск при пушах в main и dev
  pull_request:                      # запуск при PR
  schedule:
    - cron: "0 5 * * 1"             # запуск по понедельникам в 5 утра
  workflow_dispatch:                  # ручной запуск

env:
  GLOBAL_ENV: "I am visible in all jobs"

jobs:
  # ---------- JOB 1 ----------
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      artifact_name: ${{ steps.pkg.outputs.name }}
      branch_name: ${{ steps.vars.outputs.branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: vars
        name: Set branch name
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - id: pkg
        name: Create artifact
        run: |
          NAME="artifact-${GITHUB_SHA::7}.txt"
          echo "This file was built from branch $GITHUB_REF_NAME" > $NAME
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pkg.outputs.name }}
          path: ${{ steps.pkg.outputs.name }}

  # ---------- JOB 2 ----------
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      LOCAL_ENV: "I am only in this job"
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}

      - name: Show environment variables
        run: |
          echo "GLOBAL_ENV = $GLOBAL_ENV"
          echo "LOCAL_ENV = $LOCAL_ENV"
          echo "Branch from job1 = ${{ needs.build.outputs.branch_name }}"

      - name: Conditional step (only on dev branch)
        if: ${{ needs.build.outputs.branch_name == 'dev' }}
        run: echo "This runs only on DEV branch"

  # ---------- JOB 3 ----------
  matrix-job:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [14, 16]
    steps:
      - name: Matrix example
        run: |
          echo "OS = ${{ matrix.os }}"
          echo "Version = ${{ matrix.version }}"
          echo "Artifact from build = ${{ needs.build.outputs.artifact_name }}"

  # ---------- JOB 4 ----------
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # deploy стартует только после успешного build + test
    if: github.ref_name == 'main'  # только если ветка main
    steps:
      - name: Deploy step
        run: |
          echo "Deploying artifact from ${{ needs.build.outputs.artifact_name }}"
          echo "Triggered by event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"

